# Generated by Django 3.2 on 2021-08-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='Listings', to='auctions.Listing'),
        ),
    ]
