# Generated by Django 3.2 on 2021-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_user_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.AddField(
            model_name='user',
            name='wachlist',
            field=models.ManyToManyField(blank=True, related_name='wachlist', to='auctions.Listing'),
        ),
    ]
