# Generated by Django 3.2 on 2021-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210803_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(null=True, to='auctions.Listing'),
        ),
    ]
